runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /list.html/add
  script: shopping_list.app

- url: /list.html/delete-all
  script: shopping_list.app

- url: /list.html
  script: shopping_list.app
  login: required
 

- url: /.*
  script: shopping_list.app


libraries:
- name: webapp2
#this needs to be changed to the actual version!!!!!!!!!!!!!!!!x2
  version: latest
- name: jinja2
  version: latest