runtime: python27
api_version: 1
threadsafe: true

handlers:


- url: /list.html
  script: shopping_list.app
  login: required
 
- url: /static
  static_dir: static

- url: /.*
  script: shopping_list.app


libraries:
- name: webapp2
#this needs to be changed to the actual version!!!!!!!!!!!!!!!!x2
  version: 2.3
- name: jinja2
  version: 2.6